### PR TITLE
Bump to upstream 'e869c5fe'

### PR DESCRIPTION
**Pull request by mgehre-amd**
This bumps enough of upstream so that the merge-base is compatible with our LLVM version (with https://github.com/Xilinx/llvm-project/pull/214)

### CODE REVIEW

**Comment by cferry-AMD** [comment]
`e869c5fe` bumps the LLVM submodule of ONNX-MLIR. Shouldn't we also incorporate this bump?

**Comment by mgehre-amd** [comment]
> `e869c5fe` bumps the LLVM submodule of ONNX-MLIR. Shouldn't we also incorporate this bump?

Yes, good observation. I'm waiting for https://github.com/Xilinx/llvm-project/pull/214 to land to bump to that merge here. This is also why the tests on this PR still fail.

**Comment by cferry-AMD** [comment]
Automation gave me `a4f8191f09077832bdc8a28b7dc4d805e9685176` as a last good commit to merge to, which is just one commit after the merge base `2cc3f15b0d8a3d5157c5721d618f44a629cd6d5a`. We can take this but I see little value in making a bump for one commit... so I guess we're pretty much blocked on ONNX-MLIR until there is an LLVM bump. What do you think?

**Comment by mgehre-amd** [comment]
> Automation gave me `a4f8191f09077832bdc8a28b7dc4d805e9685176` as a last good commit to merge to, which is just one commit after the merge base `2cc3f15b0d8a3d5157c5721d618f44a629cd6d5a`. We can take this but I see little value in making a bump for one commit... so I guess we're pretty much blocked on ONNX-MLIR until there is an LLVM bump. What do you think?

Yes, we can let onnx-mlir be until we have a newer LLVM version; if we also cannot bump LLVM, we could also go to a newer onnx-mlir while manually keeping it compatible with an older LLVM version (usually those are only a few changes).

**Review by cferry-AMD — APPROVED** [review]
- [ ] Bump enough of LLVM for this to work

**Pull request closed without merging**
